FROM maven:3.5.3-jdk-10 AS build
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package


FROM openjdk:8u191-jre-alpine
VOLUME /tmp
COPY --from=build /usr/src/app/target/docker-java-cpu-memory-limit-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
CMD /usr/bin/java -jar app.jar -Djava.security.egd=file:/dev/./urandom
